# config/application.yml
defaults: &defaults
  marketstack:
    keys: 
      key1: 3ec1ad54862f4a08b3c9da782cad3db5  
    api: http://api.marketstack.com/v1/

development:
  <<: *defaults
  neat_setting: 800

test:
  <<: *defaults

production:
  <<: *defaults